import { League } from '@/src/core/domain/entities/league';
import { ILeagueRepository } from '@/src/core/domain/repositories/league.repository';

export interface CreateLeagueRequest {
  name: string;
  description?: string;
  isActive: boolean;
  imageUrl?: string;
  userId: string;
}

export interface CreateLeagueResponse {
  success: boolean;
  data?: League;
  error?: string;
}

export class CreateLeagueUseCase {
  constructor(private leagueRepository: ILeagueRepository) { }

  async execute(request: CreateLeagueRequest): Promise<CreateLeagueResponse> {
    try {
      // Validate required fields
      if (!request.name.trim()) {
        return { success: false, error: "League name is required" };
      }

      if (!request.userId) {
        return { success: false, error: "User ID is required" };
      }

      // Create the league entity using the static create method
      const league = League.create(
        '', // ID will be generated by repository
        request.name,
        request.userId,
        {
          description: request.description,
          isActive: request.isActive,
        }
      );

      // Save through repository
      const savedLeague = await this.leagueRepository.create(league);

      return { success: true, data: savedLeague };
    } catch (error) {
      console.error("Error creating league:", error);
      return { success: false, error: "Failed to create league" };
    }
  }
}
